name: mvn package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 8
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
          #cache-dependency-path: pom.xml

      - name: Build with Maven
        run: mvn -B package
